version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_NAME=TinkerlyDB
      - DB_USER=Admin
      - DB_PASS=12345678
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: TinkerlyDB
      MYSQL_USER: Admin
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data: